
import { Metadata } from "next";
import DiscoverComp from "../_components/Discover";

type Props = {};

export const metadata: Metadata = {
  title: "Discover",
  description: "Generated by create next app",
};
const Discover = (props: Props) => {
  return (
    <>
      <DiscoverComp />
    </>
  );
};

export default Discover;
