import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavigation from "@/components/SideNavigation/SideNavigation";
import { Provider } from "jotai";
import SessionProvider from "../components/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <SessionProvider session={session}>
      <Provider>
        <html lang="en">
          <body>
            <div className="flex h-full min-h-[100vh] overflow-hidden">
              <SideNavigation />
              {children}
            </div>
          </body>
        </html>
      </Provider>
    </SessionProvider>
  );
}
